### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by schorfES** [editorconfig/editorconfig-core-js#25]
The README.md is not up-to-date. For example:

``` javascript
$ node
> var editorconfig = require('./editorconfig');
undefined
> editorconfig.parse('/home/zoidberg/humans/anatomy.md');
{ charset: 'utf-8',
    insert_final_newline: 'true',
    end_of_line: 'lf',
    tab_width: '8',
    trim_trailing_whitespace: 'sometimes' }
```

The `parse` function now returns a promise.

**Comment by Glavin001** [comment]
+1! I updated my dependencies and now my package, [atom-beautify](https://github.com/Glavin001/atom-beautify), is broken. Upon examination I discovered that it was returning a Promise. I am not sure what other changes have been made and undocumented, and I hope that they are all documented soon.

**Comment by xuhdev** [comment]
@schorfES  I believe that the documentation has been updated a lot. is this still an issue now?

**Comment by schorfES** [comment]
Yes, I think the documentation now covers all my issues. Thanks for asking, I will close this now...
