### ISSUE TITLE
Parse string

### ISSUE THREAD

**Issue by userpixel** [editorconfig/editorconfig-core-js#43]
I like [editorconfig-parser](https://www.npmjs.com/package/editorconfig-parser) but I rather use the official one. Turns out [you have that function](https://github.com/editorconfig/editorconfig-core-js/blob/master/lib/ini.js#L65) it's just [not documented](https://github.com/editorconfig/editorconfig-core-js/blob/master/README.md).

Is it not safe to use? Is it just missing from the docs?
I'd be glad to make a PR if one of the maintainers can give a direction. @treyhunner @jedmao

**Comment by jedmao** [comment]
Totally safe to use, just not documented. That would be awesome if you submitted a PR, thanks!

**Comment by userpixel** [comment]
on it 👍
