### ISSUE TITLE
parseString is documented but not on public API

### ISSUE THREAD

**Issue by platinumazure** [editorconfig/editorconfig-core-js#46]
Am I missing something? The README.js [mentions a `parseString()` function in the public API](https://github.com/editorconfig/editorconfig-core-js/blob/09929eb84ee65b2426d5783881e68b75f4f5f2bb/README.md), but I can't actually use it:

```js
const editorconfig = require("editorconfig");
console.log(typeof editorconfig.parseString);   // expected: function, actual: undefined
```

Are there plans to expose this on the public API? (I would love to see it out there and am happy to write a pull request if it would be accepted.)

**Comment by jedmao** [comment]
It's definitely supposed to work. See https://github.com/editorconfig/editorconfig-core-js/blob/master/lib/ini.js#L43.

**Comment by platinumazure** [comment]
Hi @jedmao, thanks for the fast reply. It is true that `parseString` is exposed from lib/ini.js, but it is not exposed in the main file and that file is what gets imported when you do `require("editorconfig")`.

If you definitely want it to be exposed, I'm happy to write a PR to expose it from the main file. Let me know.

**Comment by jedmao** [comment]
Oh, good point. I think if there's a practical use case for it to be used externally then it could do no harm, but I have to ask, what is your use case?

**Comment by platinumazure** [comment]
@jedmao I'm writing a plugin for [ESLint](http://eslint.org), which is a JavaScript linting tool. This plugin will read .editorconfig files and convert (a subset of) the property keys/values into ESLint stylistic rule configurations. This would allow users to simply use their .editorconfig for configuring ESLint's stylistic rules (where there is a clear equivalent in .editorconfig).

The exposed API methods are more suited for editor integrations, where I supply a file path and the editorconfig core code will traverse up from that directory and read ancestor files. I'm going the opposite direction-- from the top down, and I need to read all subdirectories for all files to create my result.

Usual use case: Combine ancestor .editorconfig files to determine expected editor configuration *for one file*

My use case: Read all .editorconfig files *in a project* and effectively generate a top-level .editorconfig-like structure that takes nested .editorconfig files into account

Example: If I have a top-level .editorconfig file that applies to `**/*.js` and has some rules, and then I have a nested .editorconfig in tests/specs that applies to `**/*.js` and has some overrides, I would want to generate a structure similar to the below:

```json
{
    "**/*.js": {
        "indent_size": 4
    },
    "tests/specs/**/*.js": {
        "indent_size": 2
    }
}
```

As far as I can tell, I just need to read each file, call `parseString`, and do my computations.

I was wondering about `parseFromFilesSync`, but it looks like that API still requires a single file path (i.e., the single file we assume the user wants to edit). In my case, I would be calculating this for glob patterns rather than individual files and all I need is the ability to parse the .editorconfig into the JS object.

Hope this makes some sense. If there's a better way to do this, I'm all ears.

**Comment by jedmao** [comment]
It makes sense but it's concerning because it's completely backwards from the way EC parses files, as you know. With EC any overrides would be applied higher up the directory structure, not lower as you have it. I'm afraid users would be extremely confused at the results and it would cause a lot of issues. What do you think?

**Comment by platinumazure** [comment]
@jedmao Apologies, I might have introduced some confusion by going into too much detail. I do plan to work within ESLint's capabilities to ensure the correct overrides are applied. It so happens that ESLint will apply configurations such that the bottom ones override the top ones. In other words, the nested .editorconfig will override the top-level .editorconfig. Hope this makes sense.

**Comment by jedmao** [comment]
I think as long as that strategy is only applied for ESLint settings it should be fine. Feel free to submit a PR.
