### ISSUE TITLE
Let's bump to v1.0.0!

### ISSUE THREAD

**Issue by vvakame** [editorconfig/editorconfig-core-js#54]
I think this package became a stable. isn't it?

**Comment by jedmao** [comment]
No. If you updated the tests subproject you'll see there are 4 tests that this core does not support. Unfortunately, the fnmatch.js file is a bit crazy, so I'm not sure how to fix. Also, I'm on Windows and the tests are a bit finicky.

**Comment by hildjj** [comment]
As of #105, everything works on windows with the latest tests, except for `braces_closing_in_beginning`, which I think is incorrect in the test suite.  My plan is to close out existing issues, then work toward a 1.0 release.

**Comment by hildjj** [comment]
My plan is to merge #107 and #109 in that order, then do a 1.0 release.  Since those change the README file, I don't want to have a long soak time between landing them and doing a release.

If anyone disagrees with that approach, please speak up.

**Comment by hildjj** [comment]
Hearing no objections, I'm moving forward with this plan this afternoon.

**Comment by hildjj** [comment]
Publishing the package is waiting on authorization bits, which I should have known to get done beforehand.

**Comment by hildjj** [comment]
Version 1.0.0 published, release created on GitHub.
