### ISSUE TITLE
Why `@types/node` and `@types/semver` are in `dependencies`?

### ISSUE THREAD

**Issue by JounQin** [editorconfig/editorconfig-core-js#69]
As title.

**Comment by jedmao** [comment]
I forget where, but Microsoft suggests all `@types/xxx` be installed as dependencies and _not_ dev dependencies. I can't find the post right now though and, quite honestly, I'm not sure I 100% agree w/ the recommendation.

**Comment by JounQin** [comment]
I can't see any benefit for it.

**Comment by jedmao** [comment]
I totally agree with you and [this guy](https://stackoverflow.com/a/46011417/129847).

**Comment by igrayson** [comment]
The example you've linked is an argument for declaring types in your `dependencies` which you re-export as part of your interface (i.e., typings required for your consumers to understand your interface).

editorconfig does not expose any `semver` (or `node`?) typings on its interface.

Adding `@types/semver` to our dependency closure broke our build in a fashion entirely unrelated to editorconfig.

**Comment by eknowles** [comment]
it should be removed, @types/commander also
