### ISSUE TITLE
Please release commit 188a8e4bda06f2653557fa28c8bacc549e10645b

### ISSUE THREAD

**Issue by jsamr** [editorconfig/editorconfig-core-js#74]
I'm being affected by the #69 issue very indirectly (with `react-native-version`, which depends on `js-beautify`, which depends on `editorconfig`) because **the global namespace is being invaded by node types, which conflicts with react-native globals**.

You are absolutely right that you should publish type dependencies, **except those who pollute the global namespace**. Anyway, would be great to release this, so that I, and many other users, don't have TS typings breaking.

**Comment by bard** [comment]
Same here, I tried to build an ES5-only TypeScript project with parcel and suddenly non-ES5 code started compiling silently, because parcel depends on -> serialize-to-js -> js-beautify -> editorconfig. Please consider releasing.

**Comment by jedmao** [comment]
Published as v0.15.3.
