### ISSUE TITLE
"editorconfig FILEPATH1" not formatting the file on MacOS

### ISSUE THREAD

**Issue by JoseluGames** [editorconfig/editorconfig-core-js#77]
I have Node.js v12.10.0 and EditorConfig v0.15.3 installed, macOS Mojave v10.14.6 and trying to format a document using the command line seems to be doing nothing.

This my .editorconfig file:
https://pastebin.com/uxdGjssU

**Comment by jedmao** [comment]
EditorConfig doesn't format files. I'm afraid you've submitted this issue to the wrong project. What command are you running to format a file? Submit the issue to that project instead.
